server:
  port: 8051

spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    tomcat:
      max-idle: 50
      min-idle: 10
      max-wait: 10000
      max-active: 100

mybatis:
  mapper-locations: mapper/*Mapper.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
