server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://eureka-8001:8001/eureka/,http://eureka-8002:8002/eureka/,http://eureka-8003:8003/eureka/
spring:
  application:
    name: front-end
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
    suffix: .html