spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    tomcat:
      max-idle: 50
      min-idle: 10
      max-wait: 10000
      max-active: 100
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
    suffix: .html

mybatis:
  mapper-locations: mapper/*Mapper.xml