server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka


spring:
  application:
    name: springcloud-zuul


zuul:
  routes:
#   修改微服务路由访问规则
    PROVIDER: /note-provider/**
    CONSUMER: /note-consumer/**
#   屏蔽直接使用微服务名称的方式访问
  ignored-services: "*"
#  屏蔽指定的URI
#  ignored-patterns:
#  屏蔽掉指定的敏感头信息，其会将原来默认的Cookie、SetCookie、Authorization敏感头信息放开
  sensitive-headers: token
  # 使用ratelimit方式限流
  ratelimit:
    enabled: true
    # 在1个(quota)单位(refresh-interval，单位是秒)的时间窗内通过zuul的用户数量(user)、ip数量(origin)和url数量(url)，
    # 都不能超过3个(limit)，这里可以用作防止表单重复提交，导入ratelimit依赖后进行这里的配置就可以了，如果出现问题可以定义一个
    # 固定的处理页面，在resources下创建一个public/err/429.html的异常页面，这种方式比起令牌桶更加的细粒度化
    default-policy:
      quota: 1
      refresh-interval: 3
      limit:  3
      type: user,origin,url