server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
spring:
  application:
    name: consumer

# 指定feign的连接和读取超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true

# 更改ribbon负载均衡策略
#PROVIDER:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.demo.configuration.rule.CustomIRule

# 设置hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
