server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-8001:8001/eureka/,http://eureka-8002:8002/eureka/,http://eureka-8003:8003/eureka/
spring:
  application:
    name: shopping-zuul

zuul:
  routes:
    MAIN: /main/**
    FRONT-END: /front-end/**
    static:
      path: /static/**
  ignored-services: "*"
#  屏蔽指定的URI
#  ignored-patterns:
  sensitive-headers: token
  ratelimit:
    enabled: true
    default-policy:
      quota: 1
      refresh-interval: 3
      limit: 2
      type: user,origin,url