server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka-8001:8001/eureka/,http://eureka-8002:8002/eureka/,http://eureka-8003:8003/eureka/
spring:
  application:
    name: main
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    tomcat:
      max-idle: 50
      min-idle: 10
      max-wait: 10000
      max-active: 100
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
    suffix: .html
  redis:
      host: 192.168.1.148
      port: 6379
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0
mybatis:
  mapper-locations: mapper/*Mapper.xml